name: themagicvocals
favicon: null
layout_spectrum: 0
typography_spectrum: 0.08565
title: 'The Magic - Unique Vocals & Solo Instruments'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#808080'
    - '#484848'
    - '#bfbfbf'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
