name: themagicvocals
favicon: null
layout_spectrum: 0
typography_spectrum: 0.08565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22368391300551593
  lightness: 0.37197090103290975
  saturation: 0.9514168729074299
  rhythmicContrast: 0.3285567897837609
purpose: []
